### ISSUE TITLE
acme-client port was removed

### ISSUE THREAD

**Issue by contradictioned** [JoergFiedler/freebsd-jailed-nginx#3]
Hi,

just wanted to let you know [acme-client](https://www.freshports.org/security/acme-client) was removed. So the [package installation](https://github.com/JoergFiedler/freebsd-jailed-nginx/blob/master/tasks/nginx-letsencrypt.yml#L2) does not work and probably the rest of the let's encrypt handling needs to be adjusted to another client.

**Comment by JoergFiedler** [comment]
Hi,

@contradictioned thanks for the heads up … seems I really need to migrate to something else, will investigate … also create a monthly trigger for Travis-CI to discover those changes automativally … Thank you again.

**Comment by JoergFiedler** [comment]
@contradictioned finally I managed to fix it … thanks for the hint again
